package:
    name: simglibpy
    version: "0.0.1"
  
source:
  git_url: https://github.com/sylvainprigent/simglibpy.git
  git_rev: v0.0.1
  
build:
  number: 1
  
requirements:
  build:
    - python
    - setuptools
    - simglib
    - numpy
    - scipy
    - cython
    - scikit-image
  host:
    - python
    - simglib
    - numpy
    - scipy
    - scikit-image
  run:
    - python
    - simglib
    - numpy
    - scipy
    - scikit-image
  
test:
  imports:
    - simglibpy
  
about:
  home: 'https://github.com/sylvainprigent/simglibpy'
  summary: 'Scientific multidimentional image processing library'
  license: GNU General Public License v3 (GPLv3)