package:
    name: simglibpy
    version: "0.1.1"
  
source:
  git_url: https://github.com/sylvainprigent/simglibpy.git
  git_rev: v0.1.1
  
build:
  number: 1
  
requirements:
  build:
    - python
    - setuptools
    - simglib
    - numpy>=1.21
    - scipy
    - cython >=0.28.5
    - scikit-image
    - openblas
  host:
    - python
    - simglib
    - numpy>=1.21
    - cython >=0.28.5
    - scipy
    - scikit-image
    - openblas
  run:
    - python
    - simglib
    - numpy>=1.21
    - scipy
    - scikit-image
    - openblas
  
test:
  imports:
    - simglibpy
  
about:
  home: 'https://github.com/sylvainprigent/simglibpy'
  summary: 'Scientific multidimentional image processing library'
  license: GNU General Public License v3 (GPLv3)