package:
    name: simglib
    version: "0.1.2"
  
source:
  git_url: https://github.com/sylvainprigent/simglib.git
  git_rev: v0.1.2
  
build:
  number: 1
  
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - libtiff
    - fftw
    - git
    - llvm-openmp
  host:
    - libtiff
    - fftw
  run:
    - libtiff
    - fftw
  
test:
  commands:
    - "! test -d $PREFIX/bin/simgspitfiredeconv2d"                # [unix]
    - "! test -d $PREFIX/bin/simgspitfiredeconv3d"                # [unix]
    - if not exist %PREFIX%\\bin\\simgspitfiredeconv2d.exe exit 1     # [win]
    - if not exist %PREFIX%\\bin\\simgspitfiredeconv3d.exe exit 1     # [win]
  
about:
  home: 'https://github.com/sylvainprigent/simglib'
  summary: 'Scientific multidimentional image processing library'
  license: GNU General Public License v3 (GPLv3)