name: Deploy to anaconda
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: conda-action
        uses: s-weigand/setup-conda@v1
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Lint
        shell: bash -l {0}
        run: |
            conda install cmake
            conda install make
            conda install conda-build
      - name: conda build  
        shell: bash -l {0}   
        run: |
            conda-build recipes/simglib
