name: Deploy to anaconda
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: conda-action
        uses: s-weigand/setup-conda@v1
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Lint
        shell: bash -l {0}
        run: |
            conda config --set anaconda_upload no
            conda config --add channels conda-forge
            conda config --show channels
            conda install --yes cmake
            conda install --yes make
            conda install  --yes conda-build
            conda install anaconda-client --yes
      - name: conda build linux 
        if: runner.os == 'Linux'
        shell: bash -l {0}   
        run: |
            conda-build recipes/simglib   
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u sylvainprigent  /usr/share/miniconda/conda-bld/linux-64/simglib-*.tar.bz2 --force
      - name: conda build macos 
        if: runner.os == 'macOS'
        shell: bash -l {0}   
        run: |
            conda-build recipes/simglib   
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u sylvainprigent  /usr/local/miniconda/conda-bld/osx-64/simglib-*.tar.bz2 --force
      - name: conda build windows 
        if: runner.os == 'Windows'
        run: |
            conda-build recipes/simglib   
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u sylvainprigent  /usr/share/miniconda/conda-bld/win-64/simglib-*.tar.bz2 --force
