name: Deploy to anaconda
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: conda-action
        uses: s-weigand/setup-conda@v1
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Lint
        shell: bash -l {0}
        run: |
            conda config --set anaconda_upload yes
            conda config --add channels conda-forge
            conda config --show channels
            conda install --yes cmake
            conda install --yes make
            conda install  --yes conda-build
            conda install anaconda-client --yes
      - name: publish-to-conda
        uses: meffmadd/conda-publish-action@v1.4
        with:
          subdir: 'recipes/simglib'
          anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: 'win osx linux'
