name: Deploy simglibpy to anaconda
on: [push]

jobs:
  miniconda:
    name: simglibpy ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: conda-action
        uses: s-weigand/setup-conda@v1
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Lint
        shell: bash -l {0}
        run: |
            conda config --set anaconda_upload no
            conda config --add channels conda-forge
            conda config --add channels sylvainprigent
            conda config --show channels
            conda install --yes cython
            conda install --yes numpy
            conda install --yes conda-build
            conda install anaconda-client --yes
      - name: conda build linux 
        if: runner.os == 'Linux'
        shell: bash -l {0}   
        run: |
            conda-build recipes/simglibpy   
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u sylvainprigent  /usr/share/miniconda/conda-bld/linux-64/simglibpy-*.tar.bz2 --force
      - name: conda build macos 
        if: runner.os == 'macOS'
        shell: bash -l {0}   
        run: |
            conda-build recipes/simglibpy   
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u sylvainprigent  /usr/share/miniconda/conda-bld/osx-64/simglibpy-*.tar.bz2 --force
      - name: conda build windows 
        if: runner.os == 'Windows'
        run: |
            conda-build recipes/simglibpy   
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u sylvainprigent  /usr/share/miniconda/conda-bld/win-64/simglibpy-*.tar.bz2 --force
