name: Deploy to anaconda
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: conda-action
        uses: s-weigand/setup-conda@v1
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Lint
        shell: bash -l {0}
        run: |
            export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
            conda config --set anaconda_upload yes
            conda config --add channels conda-forge
            conda config --show channels
            conda install --yes cmake
            conda install --yes make
            conda install  --yes conda-build
            conda install anaconda-client --yes
      - name: conda build  
        shell: bash -l {0}   
        run: |
            conda-build recipes/simglib   
